# 加密货币24小时监控系统配置文件
# Crypto 24h Monitor System Configuration

# 系统设置
系统配置:
  名称: "加密货币24小时监控系统"
  版本: "2.0"
  运行模式: "持续监控"  # 持续监控 | 定时任务
  日志级别: "INFO"  # DEBUG | INFO | WARNING | ERROR
  
# 监控币种设置  
监控币种:
  主要币种:
    - "BTCUSDT"    # 比特币
    - "ETHUSDT"    # 以太坊
    - "SOLUSDT"    # 币安币
  
  次要币种:


# K线数据获取设置
K线数据配置:
  获取间隔: 300         # 秒，5分钟获取一次 (15分钟K线不需要每分钟获取)
  默认时间周期: "15m"     # K线周期
  历史数据长度: 50      # 获取最近100个K线用于指标计算 (15m*100 = 25小时数据)
  数据源超时: 10        # 秒
  
# 技术指标参数
技术指标:
  RSI:
    周期: 14
    超买线: 70
    超卖线: 30
    极值超买: 80       # 1.5分钟内触发的极值
    极值超卖: 20       # 1.5分钟内触发的极值
    
  MACD:
    快线EMA: 12
    慢线EMA: 26 
    信号线: 9
    
  移动平均线:
    短期: 20
    中期: 50
    长期: 200

# 交易分析触发条件
触发条件:
  常规分析间隔: 1800     # 秒，30分钟正常分析间隔
  紧急分析冷却: 1800     # 秒，紧急分析冷却时间（每个币种独立）
  交易确认超时: 60       # 秒，Telegram交易确认超时时间
  
  特殊触发:
    RSI极值检测:
      启用: true
      检测周期: 60      # 秒，1.5分钟内检测RSI极值
      
    价格止盈止损:
      启用: true
      止盈百分比: 5.0   # %
      止损百分比: 3.0   # %
      
    触发事件清理:
      清理间隔: 300     # 秒，清理超过5分钟的旧触发事件
      
    突发新闻:
      启用: false       # 暂时不实现
      
# 风险控制
风险管理:
  最大持仓数: 6         # 同时最多持有3个仓位
  单笔最大仓位: 20.0    # %，单笔交易最大占用资金百分比
  默认杠杆: 5           # 倍
  最大杠杆: 20          # 倍
  
  # 币种专用杠杆配置
  币种杠杆:
    BTCUSDT: 20         # 比特币使用20倍杠杆
    ETHUSDT: 20         # 以太坊使用20倍杠杆
    SOLUSDT: 15         # Solana使用15倍杠杆
    ENAUSDT: 10         # ENA使用10倍杠杆
    XRPUSDT: 15         # 瑞波币使用15倍杠杆
    DOGEUSDT: 10        # 狗狗币使用10倍杠杆
    默认杠杆: 5          # 其他币种默认5倍杠杆
  
  止损设置:
    默认止损: 5.0       # %
    最大止损: 15.0      # %
    
  止盈设置:
    默认止盈: 10.0      # %
    最大止盈: 50.0      # %

# 交易员工作状态
交易员设置:
  工作状态检测: true
  最小工作间隔: 600     # 秒，10分钟
  强制休息时间: 36000    # 秒，1小时强制休息
  
# 数据库设置
数据库配置:
  文件名: "crypto_monitor.db"
  数据保留天数: 30      # 保留30天历史数据
  自动清理: true
  
# API配置
API配置:
  # 分析师专用模型配置
  分析师模型:
    技术分析师:
      # 提供商: "claude"     # claude | doubao | deepseek
      # 模型: "claude-sonnet-4-20250514"
      提供商: "doubao"
      模型: "doubao-1.6"
      最大令牌: 2000
      温度: 0.3          # 技术分析需要更精确
      
    市场分析师:
      提供商: "doubao"
      模型: "doubao-1.5-lite-32k"
      最大令牌: 1200
      温度: 0.7
      
    基本面分析师:
      提供商: "doubao"
      模型: "doubao-1.5-pro-32k"
      最大令牌: 1500
      温度: 0.5
      
    宏观分析师:
      # 提供商: "claude"
      # 模型: "claude-sonnet-4-20250514"
      提供商: "doubao"
      模型: "doubao-1.6"
      最大令牌: 1500
      温度: 0.6
      
    首席分析师:
      提供商: "doubao"
      模型: "doubao-1.6"
      最大令牌: 2000
      温度: 0.4
      
    研究部门总监:
      提供商: "doubao"
      模型: "doubao-1.6"
      最大令牌: 2000
      温度: 0.5
      
    永续交易员:
      # 提供商: "claude"
      # 模型: "claude-sonnet-4-20250514"
      提供商: "doubao"
      模型: "doubao-1.6"
      最大令牌: 2000
      温度: 0.2          # 交易决策需要更保守
  
  # 通用配置
  通用设置:
    请求超时: 60         # 秒
    流式输出: true
    
  # 兜底模型配置 - API调用失败时的备用方案
  兜底模型:
    启用: true
    提供商: "doubao"           # 备用模型提供商
    模型: "doubao-1.5-lite-32k"  # 备用模型（通常选择稳定、便宜的）
    最大令牌: 1000
    温度: 0.5
    超时: 30               # 备用模型超时时间（更短）
    重试次数: 2             # 备用模型重试次数
    说明: "当主要模型API调用失败时使用此模型"
    
  Binance:
    测试网: false       # 是否使用测试网
    请求超时: 15       # 秒
    重试次数: 3
    
  CoinGecko:
    请求间隔: 10       # 秒，避免频率限制
    
# 通知设置
通知配置:
  控制台输出: true
  日志文件: true
  
  重要事件通知:
    - "系统启动"
    - "触发特殊条件"
    - "交易执行"
    - "错误异常"

# 性能优化
性能设置:
  数据缓存: true
  分析模式: "队列"          # 队列 | 并发 - 常规分析执行模式
  队列间隔: 5              # 秒，队列模式下每个币种分析的间隔
  内存限制: 512            # MB